### ISSUE TITLE
Width 100% not running

### ISSUE THREAD

**Issue by mozhn** [NightCatSama/textarea-line-number#1]
Textarea width 100% not running.

My css code:

`.textarea {
    left: 0;
    bottom: 0;
    right: 0;
    top: 0;
    width: 100%;
    float: left;
    height: 100%;
    border: none;
    background-color: #ffffff;
    color: black;
    outline: none;
    resize: none;
}
`

**Comment by NightCatSama** [comment]
You can use the component's `width` property.
